import { VerticalBox } from "std-widgets.slint";
import { VideoPlayer } from "video_player.slint";
import { PosterItem } from "../widgets/poster_item.slint";
export component LibraryPage inherits VerticalBox {

    PosterItem {
        poster: @image-url("../../demo.webp");
        title: "The 100";
        pressed => {
            debug("The 100 pressed")
        }
    }

    PosterItem {
        poster: @image-url("../../demo.webp");
        title: "The 200";
        pressed => {
            debug("The 200 pressed")
        }
    }
}
