import { VerticalBox, GridBox, TextEdit, HorizontalBox, ComboBox, CheckBox } from "std-widgets.slint";

component FormItem inherits GridLayout {
    in property <string> label;
    spacing-horizontal: 20px;

    Text {
        colspan: 8;
        text: label;
        horizontal-alignment: right;
        vertical-alignment: center;
    }

    HorizontalLayout {
        colspan: 10;
        col: 8;
        @children
    }
}

component Form inherits VerticalBox {
    spacing: 5px;
    height: 90px;
}

export component SettingsPage inherits VerticalBox {
    TabWidget {
        Tab {
            title: "General";
            Form {
                FormItem {
                    label: "Demo 1";
                    TextEdit { }
                }

                FormItem {
                    label: "Demo 2";
                    TextEdit { }
                }
            }
        }

        Tab {
            title: "Playback";

            Form {
                FormItem {
                    label: "Auto-play next";
                    CheckBox { }
                }

                FormItem {
                    label: "Default subtitle language";

                    ComboBox {
                        model: ["None", "English", "日本語 / Japanese"];
                    }
                }

                FormItem {
                    label: "Default audio language";

                    ComboBox {
                        model: ["English", "日本語 / Japanese"];
                    }
                }

                FormItem {
                    label: "Only show subtitles ";

                    ComboBox {
                        model: ["None", "English", "日本語 / Japanese"];
                    }
                }
            }
        }

        Tab {
            title: "Appearance";
        }

        Tab {
            title: "Metadata";

            Form {
                FormItem {
                    label: "Demo";
                    TextEdit { }
                }
            }
        }
    }
}
