import { Palette, HorizontalBox, Button, ProgressIndicator } from "std-widgets.slint";

export enum LoadState {
     Fetching,
     Downloading,
     Downloaded
}
export global CurrentVideo {
    in-out property <int> name;
    in-out property <string> url;
    changed url => {
        load(url);
    }
    callback load(string);
    in-out property <image> curr: @image-url("../big_buck_bunny.jpg");
    in property <int> durationMs: 1000 * 60 * 124;
    property <int> durationSecs: durationMs / 1000;
    property <int> durationMins: durationSecs / 60;
    property <int> durationHours: durationMins / 60;

    in-out property <int> positionMs: 1000 * 60 * 12;
    property <int> positionSecs: positionMs / 1000;
    property <int> positionMins: positionSecs / 60;
    property <int> positionHours: positionMins / 60;
    in-out property <bool> playing: true;
}

export component VideoPlayer inherits FocusScope {

    key-pressed(event) => {
        debug(event.text);
        accept
    }
    VerticalLayout {

        Image {
            source: CurrentVideo.curr;
        }

        Rectangle {
            background: Palette.alternate-background;
            border-color: Palette.alternate-foreground;
            border-radius: 2px;

            box := HorizontalBox {
                spacing: 3px;
                if CurrentVideo.playing: Button {
                    icon: @image-url("../../icons/tabler--player-pause-filled.svg");
                    clicked => {
                        CurrentVideo.playing = false
                    }
                }
                if !CurrentVideo.playing:  Button {
                    icon: @image-url("../../icons/tabler--player-play-filled.svg");
                    clicked => {
                        CurrentVideo.playing = true
                    }
                }
                area := TouchArea {
                    progress := ProgressIndicator {
                        width: box.width - 5px;
                        indeterminate: false;
                        progress: CurrentVideo.positionMs / CurrentVideo.durationMs;
                    }

                    pointer-event(event) => {
                        if (event.kind == PointerEventKind.down || event.kind == PointerEventKind.up) {
                            CurrentVideo.positionMs = (area.mouse-x * CurrentVideo.durationMs) / area.width;
                        }
                    }
                    clicked => {
                        debug("change position");
                    }
                }
            }
        }
    }
}
