[package]
name = "slint-rust-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.1"
robius-directories = "5.0.1"
slint = "1.12.1"

[build-dependencies]
slint-build = "1.12.1"
