import { Palette, VerticalBox } from "std-widgets.slint";
export component PosterItem inherits Rectangle {
    background: Palette.alternate-background;
    in property <image> poster;
    in property <string> title;

    VerticalBox {
        spacing: 2px;
        Image {
            vertical-alignment: ImageVerticalAlignment.center;
            source: poster;
        }

        Text {
            horizontal-alignment: TextHorizontalAlignment.center;
            vertical-alignment: TextVerticalAlignment.bottom;
            text: title;
        }
    }
}
