import { Button, VerticalBox, CheckBox, HorizontalBox } from "std-widgets.slint";
import { NavMenu } from "menu.slint";
import { Routes } from "route.slint";
import { HomePage } from "pages/home.slint";
import { SettingsPage } from "pages/settings.slint";
import { LibraryPage } from "pages/library.slint";
import { PlaybackSettings, MySettings, Settings } from "settings.slint";
import { VideoPlayer, CurrentVideo, LoadState } from "pages/video_player.slint";
export { PlaybackSettings, MySettings, Settings, CurrentVideo, LoadState }
export component AppWindow inherits Window {
    title: "BeWatch";
    in-out property <int> counter: 42;
    callback request-increase-value();
    HorizontalBox {

        NavMenu { }

        if Routes.currPath == "/": VideoPlayer { }
        if Routes.currPath == "/library": LibraryPage { }
        if Routes.currPath == "/settings": SettingsPage { }
    }
}
